language: python
python:
  - "3.4"
addons:
  - postgres: "9.4"
sudo: false
cache: pip
before_script:
  - psql -c 'create database garfield;' -U postgres
  - psql -c 'create database fsmi;' -U postgres
  - ./fill_data.py
script: ./run_tests.sh
